import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  scrollContent: {
    paddingBottom: 100,
  },
  mapContainer: {
    width: '92%',
    height: 320,
    position: 'relative',
    borderRadius: 20,
    overflow: 'hidden',
    marginHorizontal: 16,
    marginBottom: 70,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  currentLocationButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  currentLocationGradient: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationContainer: {
    backgroundColor: '#fff',
    borderRadius: 24,
    margin: 16,
    marginTop: -50,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    zIndex: 1,
  },
  locationInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 16,
    marginBottom: 1,
  },
  pickupInput: {
    backgroundColor: '#EBF5FF',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  dropoffInput: {
    backgroundColor: '#FFF2F2',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  locationIcon: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    marginRight: 12,
  },
  pickupIcon: {
    backgroundColor: '#007AFF',
  },
  dropoffIcon: {
    backgroundColor: '#FF3B30',
  },
  locationDivider: {
    width: 2,
    height: 30,
    backgroundColor: '#E5E5EA',
    position: 'absolute',
    left: 31,
    top: '50%',
    transform: [{ translateY: -15 }],
    zIndex: 2,
  },
  locationContent: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 12,
    marginBottom: 4,
    color: '#8E8E93',
  },
  locationText: {
    fontSize: 16,
    color: '#1C1C1E',
    fontWeight: '500',
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#1c1c1e',
  },
  dropoffButton: {
    flex: 1,
    justifyContent: 'center',
  },
  placeholderText: {
    color: '#8E8E93',
  },
  clearButton: {
    padding: 8,
    marginLeft: 8,
  },
  recentLocations: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 8,
  },
  recentLocationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 8,
  },
  recentLocationText: {
    marginLeft: 12,
    flex: 1,
  },
  recentLocationName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1c1c1e',
    marginBottom: 4,
  },
  recentLocationAddress: {
    fontSize: 14,
    color: '#8e8e93',
  },
  rideOptionsContainer: {
    marginBottom: 16,
  },
  rideTypeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1c1c1e',
  },
  distanceText: {
    fontSize: 14,
    color: '#8e8e93',
  },
  rideTypesScroll: {
    paddingHorizontal: 8,
  },
  rideTypeCard: {
    width: width * 0.4,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  selectedRideTypeCard: {
    borderColor: '#007AFF',
    borderWidth: 2,
    shadowColor: '#007AFF',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  rideTypeIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: '#F2F2F7',
  },
  selectedRideTypeIcon: {
    backgroundColor: '#007AFF',
  },
  rideTypeName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1c1c1e',
    marginBottom: 4,
  },
  selectedRideTypeText: {
    color: '#007AFF',
  },
  rideTypePrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#34C759',
    marginBottom: 8,
  },
  rideTypeCapacity: {
    fontSize: 14,
    color: '#3A3A3C',
    marginBottom: 8,
    fontWeight: '500',
  },
  rideTypeFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  rideTypeFeature: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 4,
  },
  featureDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  featureText: {
    fontSize: 13,
    color: '#636366',
    fontWeight: '500',
  },
  additionalOptions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 16,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    transform: [{ scale: 1 }],
  },
  optionButtonText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
    color: '#1c1c1e',
  },
  promoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  promoInput: {
    flex: 1,
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    marginRight: 12,
    fontSize: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  promoButton: {
    width: 100,
  },
  notesInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    height: 100,
    textAlignVertical: 'top',
    fontSize: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  bookButtonContainer: {
    margin: 16,
    marginTop: 24,
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  bookButtonDisabled: {
    opacity: 0.7,
    shadowOpacity: 0.1,
  },
  bookButtonGradient: {
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  bookButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookButtonIcon: {
    marginRight: 12,
  },
  bookButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginRight: 12,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#fff',
    marginTop: 40,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5EA',
    zIndex: 1,
  },
  modalCloseButton: {
    padding: 8,
    borderRadius: 8,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#000',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 8,
  },
  paymentMethodItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    marginBottom: 12,
    backgroundColor: '#f8f9fa',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    transform: [{ scale: 1 }],
  },
  selectedPaymentMethod: {
    backgroundColor: '#E8F3FF',
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  paymentMethodName: {
    marginLeft: 16,
    fontSize: 16,
    color: '#1c1c1e',
  },
  selectedPaymentMethodText: {
    color: '#1c1c1e',
    fontSize: 16,
    marginLeft: 12,
  },
  swipeButtonContainer: {
    marginHorizontal: 16,
    marginBottom: 24,
    marginTop: 12,
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  swipeRail: {
    borderRadius: 32,
    borderWidth: 0,
    backgroundColor: '#fff',
    height: 64,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  swipeButtonText: {
    fontFamily: Platform.select({ ios: 'System', android: 'Roboto' }),
    fontWeight: '600',
    fontSize: 18,
    color: '#007AFF',
  },
  swipeButtonTextDisabled: {
    color: '#8E8E93',
  },
  swipeRailDisabled: {
    backgroundColor: '#F2F2F7',
    shadowOpacity: 0.05,
    elevation: 2,
  },
  locationSelectionMap: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  selectedLocationContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    padding: 16,
    paddingVertical: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  selectedLocationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFE5E5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedLocationText: {
    flex: 1,
    marginLeft: 12,
    fontSize: 15,
    color: '#000',
    lineHeight: 20,
  },
  modalConfirmButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  modalConfirmButtonDisabled: {
    backgroundColor: '#E5E5EA',
  },
  modalConfirmText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
  },
  modalConfirmTextDisabled: {
    color: '#8E8E93',
  },
}); 
